spring.application.name=WorkFromHome
#logging.level.org.springframework=DEBUG

#excel.config-file=config.csv

excel.filepath=classpath:data/Employee_List.xlsx
excel.sheetNames=Employees
excel.sheetDays=Days
excel.sheetEmail=Email

server.port=8091
